#!/bin/bash

zlog=elements/ZLog.swf
test=elements/test.swf

rm $zlog
rm $test

echo "*** MTASC ***"
mtasc -swf $zlog -header 1:1:31 -version 8 -strict -cp /home/zarate/projects/as2/ -main ZLog.as
mtasc -swf $test -header 500:40:31 -version 8 -strict -cp /home/zarate/projects/as2/ -main test.as -trace tv.zarate.Utils.Trace.trc