#!/bin/bash

swfpath="/home/zarate/Desktop/www/zplayer/supernovaplayer.swf"
zpath="../../../"

rm $swfpath

swfmill simple supernova.xml $swfpath

mtasc -swf $swfpath -version 8 -strict -cp $zpath snModel.as -main -trace tv.zarate.utils.Trace.trc